import { NextRequest, NextResponse } from 'next/server';
import JSZip from 'jszip';
import { exportRequestSchema } from '@/lib/validators';
import { createApiContext } from '@/lib/apiContext';
import { RATE_LIMIT_CONFIGS } from '@/lib/rateLimit';

export async function POST(request: NextRequest) {
    const ctx = createApiContext(request, RATE_LIMIT_CONFIGS.general);
    if (ctx.rateLimitResponse) {
        return ctx.finalize(ctx.rateLimitResponse);
    }

    try {
        const body = await request.json();

        // Validate request
        const validationResult = exportRequestSchema.safeParse(body);
        if (!validationResult.success) {
            return ctx.finalize(NextResponse.json(
                { success: false, error: validationResult.error.message },
                { status: 400 }
            ));
        }

        const { projectName, outputs, metadata } = validationResult.data;

        const zip = new JSZip();
        const sanitizedName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_');

        // Create project folder
        const folder = zip.folder(sanitizedName);
        if (!folder) {
            return ctx.finalize(NextResponse.json(
                { success: false, error: 'Failed to create zip folder' },
                { status: 500 }
            ));
        }

        // Add README
        const readmeContent = `# ${projectName}

Generated by Sketch.AI - AI-powered hardware design assistant

## Project Overview

${metadata ? `
- **Estimated Cost**: $${metadata.estimatedCost}
- **Complexity**: ${metadata.complexity}
- **Build Time**: ${metadata.buildTime}
` : 'No metadata available'}

## Contents

${outputs.bom ? '- `Bill-of-Materials.md` - Complete component list' : ''}
${outputs.assembly ? '- `Assembly-Instructions.md` - Step-by-step build guide' : ''}
${outputs.firmware ? '- `firmware/` - Microcontroller code' : ''}
${outputs.schematic ? '- `Schematic.md` - Circuit design description' : ''}
${outputs.safety ? '- `Safety-Review.md` - Safety compliance report' : ''}
${outputs.sustainability ? '- `Sustainability.md` - Environmental impact analysis' : ''}
${outputs['cost-optimization'] ? '- `Cost-Optimization.md` - Cost optimization report' : ''}
${outputs.dfm ? '- `DFM-Analysis.md` - Design for Manufacturing notes' : ''}
${outputs.marketing ? '- `Marketing-Brief.md` - Marketing copy' : ''}
${outputs['patent-risk'] ? '- `Patent-Risk.md` - Patent/IP risk analysis' : ''}

## Getting Started

1. Review the Bill of Materials and source components
2. Follow the Assembly Instructions step by step
3. Flash the firmware to your microcontroller
4. Test and enjoy your project!

---

*Generated by [Sketch.AI](https://sketch.ai) - Transform hardware ideas into reality*
`;

        folder.file('README.md', readmeContent);

        // Add outputs
        if (outputs.bom) {
            folder.file('Bill-of-Materials.md', outputs.bom);
        }

        if (outputs.assembly) {
            folder.file('Assembly-Instructions.md', outputs.assembly);
        }

        if (outputs.firmware) {
            const firmwareFolder = folder.folder('firmware');
            if (firmwareFolder) {
                // Extract filename from firmware if present, or use default
                const firmwareFilename = outputs.firmware.includes('.ino')
                    ? `${sanitizedName}.ino`
                    : `${sanitizedName}.ino`;
                firmwareFolder.file(firmwareFilename, outputs.firmware);
            }
        }

        if (outputs.schematic) {
            folder.file('Schematic.md', outputs.schematic);
        }

        if (outputs.safety) {
            folder.file('Safety-Review.md', outputs.safety);
        }

        if (outputs.sustainability) {
            folder.file('Sustainability.md', outputs.sustainability);
        }

        if (outputs['cost-optimization']) {
            folder.file('Cost-Optimization.md', outputs['cost-optimization']);
        }

        if (outputs.dfm) {
            folder.file('DFM-Analysis.md', outputs.dfm);
        }

        if (outputs.marketing) {
            folder.file('Marketing-Brief.md', outputs.marketing);
        }

        if (outputs['patent-risk']) {
            folder.file('Patent-Risk.md', outputs['patent-risk']);
        }

        if (outputs['scene-json']) {
            folder.file('scene_model.json', outputs['scene-json']);
        }

        // Generate ZIP
        const zipBlob = await zip.generateAsync({
            type: 'arraybuffer',
            compression: 'DEFLATE',
            compressionOptions: { level: 9 },
        });

        // Return as downloadable file
        return ctx.finalize(new NextResponse(zipBlob, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': `attachment; filename="${sanitizedName}.zip"`,
            },
        }));

    } catch (error) {
        console.error('Export error:', error);
        ctx.logError(error as Error);

        return ctx.finalize(NextResponse.json(
            { success: false, error: 'Failed to generate export file' },
            { status: 500 }
        ));
    }
}
