import { NextRequest, NextResponse } from 'next/server';
import { buildGuideRequestSchema } from '@/lib/validators';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();

        const validationResult = buildGuideRequestSchema.safeParse(body);
        if (!validationResult.success) {
            return NextResponse.json(
                { success: false, error: validationResult.error.message },
                { status: 400 }
            );
        }

        const { projectName, outputs, metadata } = validationResult.data;
        const sanitizedName = projectName.replace(/[^a-zA-Z0-9-_]/g, '_');

        const sections = [
            `# ${projectName} Build Guide`,
            'Generated by Sketch.ai',
            '## Project Overview',
            metadata
                ? `- **Estimated Cost**: $${metadata.estimatedCost}\n- **Complexity**: ${metadata.complexity}\n- **Build Time**: ${metadata.buildTime}`
                : '_No metadata available._',
            '## Bill of Materials',
            outputs.bom ? outputs.bom : '_BOM not generated yet._',
            '## Assembly Instructions',
            outputs.assembly ? outputs.assembly : '_Assembly instructions not generated yet._',
            '## Schematic',
            outputs.schematic ? outputs.schematic : '_Schematic not generated yet._',
        ];

        const content = sections.join('\n\n');

        return new NextResponse(content, {
            status: 200,
            headers: {
                'Content-Type': 'text/markdown; charset=utf-8',
                'Content-Disposition': `attachment; filename="${sanitizedName}-build-guide.md"`,
            },
        });
    } catch (error) {
        console.error('Build guide error:', error);
        return NextResponse.json(
            { success: false, error: 'Failed to generate build guide' },
            { status: 500 }
        );
    }
}
