export type DemoSketch = {
    id: string;
    title: string;
    description: string;
    imageUrl: string;
    prompt: string;
    presetId?: string;
    hidden?: boolean;
};

export const demoSketches: DemoSketch[] = [
    {
        id: 'smart-tracker-tag',
        title: 'Smart Tracker Tag',
        description: 'Exploded Bluetooth tracker with USB-C, LED, and lanyard loop.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'smart-tracker-tag',
    },
    {
        id: 'puck-sensor',
        title: 'Puck Sensor',
        description: 'Exploded puck sensor with USB-C and PCB stack.',
        imageUrl: '/demo/puck-sketch.svg',
        prompt: 'Compact puck sensor with USB-C, status LED, round PCB, and an exploded enclosure view.',
        presetId: 'puck-sensor',
    },
    {
        id: 'earbuds-case',
        title: 'Earbuds Charging Case',
        description: 'Rectangular clam-shell case with earbud cradles and Qi coil.',
        imageUrl: '/demo/earbuds-case.svg',
        prompt: 'Wireless earbuds charging case with hinged lid, earbud cradles, Qi charging coil, battery, PCB, USB-C port, and LED indicator.',
        presetId: 'earbuds-case',
    },
    {
        id: 'game-controller',
        title: 'Game Controller',
        description: 'Single-hand gamepad with analog stick and face buttons.',
        imageUrl: '/demo/game-controller.svg',
        prompt: 'Compact single-hand game controller with analog stick, 4 face buttons, shoulder trigger, rumble motor, battery, Bluetooth PCB, and USB-C.',
        presetId: 'game-controller',
    },
    {
        id: 'sensor-hub',
        title: 'Sensor Hub Tower',
        description: 'Vertical sensor tower with grille, OLED display, and dual-PCB stack.',
        imageUrl: '/demo/sensor-hub.svg',
        prompt: 'Smart home environment sensor hub tower with perforated grille, sensor cluster, OLED display, dual-PCB stack, battery compartment, and weighted base.',
        presetId: 'sensor-hub',
    },
    {
        id: 'iot-puck-device',
        title: 'IoT Puck Device',
        description: 'Round IoT puck with USB-C, LED, and lanyard loop.',
        imageUrl: '/demo/iot-puck-device.svg',
        prompt: 'Round IoT puck device with USB-C charging, status LED, lanyard loop, round PCB, and an exploded enclosure view.',
        presetId: 'iot-puck-device',
        hidden: true,
    },
    {
        id: 'sensor-puck',
        title: 'Sensor Puck',
        description: 'Round device with USB-C and status LED.',
        imageUrl: '/demo/sensor-puck.svg',
        prompt: 'Round sensor puck with a USB-C port, tiny status LED, and internal PCB.',
        hidden: true,
    },
    {
        id: 'enclosure-usb-led',
        title: 'USB-C LED Enclosure',
        description: 'Compact enclosure with a status LED and USB-C port.',
        imageUrl: '/demo/enclosure-usb-led.svg',
        prompt: 'Compact electronics enclosure with a USB-C port and a small status LED.',
        hidden: true,
    },
    {
        id: 'sensor-box',
        title: 'Sensor Node',
        description: 'Weather sensor box with vents and dual sensors.',
        imageUrl: '/demo/sensor-box.svg',
        prompt: 'Weather sensor node housing with a vented lid and two external sensors.',
        hidden: true,
    },
    {
        id: 'teddy-bear',
        title: 'Teddy Bear Toy',
        description: 'Organic plush toy with round ears and eyes.',
        imageUrl: '/demo/teddy-bear.svg',
        prompt: 'A cute teddy bear plush toy with round ears, big eyes, and short arms.',
        hidden: true,
    },
    {
        id: 'bracket',
        title: 'Mounting Bracket',
        description: 'Simple L-bracket with three screw holes.',
        imageUrl: '/demo/bracket.svg',
        prompt: 'L-shaped mounting bracket with three screw holes and a reinforced corner.',
        hidden: true,
    },
    {
        id: 'codexv1',
        title: 'codexv1',
        description: 'Direct primitive clone of the sample.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv1',
        hidden: true,
    },
    {
        id: 'codexv2',
        title: 'codexv2',
        description: 'Layer-composed reconstruction clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv2',
        hidden: true,
    },
    {
        id: 'codexv3',
        title: 'codexv3',
        description: 'JSON round-trip reconstructed clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv3',
        hidden: true,
    },
    {
        id: 'codexv4',
        title: 'codexv4',
        description: 'Quantized CAD-grid clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv4',
        hidden: true,
    },
    {
        id: 'codexv5',
        title: 'codexv5',
        description: 'Parametric shell + canonical internals clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv5',
        hidden: true,
    },
    {
        id: 'codexv6',
        title: 'codexv6',
        description: 'Unlit-shell material strategy clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv6',
        hidden: true,
    },
    {
        id: 'codexv7',
        title: 'codexv7',
        description: 'Rounded micro-component remesh clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv7',
        hidden: true,
    },
    {
        id: 'codexv8',
        title: 'codexv8',
        description: 'Accent-ring overlay clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv8',
        hidden: true,
    },
    {
        id: 'codexv9',
        title: 'codexv9',
        description: 'Tolerance-jitter robustness clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv9',
        hidden: true,
    },
    {
        id: 'codexv10',
        title: 'codexv10',
        description: 'Hybrid fusion pipeline clone.',
        imageUrl: '/demo/smart-tracker-tag.svg',
        prompt: 'Round smart tracker tag with USB-C, status LED, lanyard loop, and an exploded enclosure view.',
        presetId: 'codexv10',
        hidden: true,
    },
];
